[[settings]]
[settings.up]
bandwidth=0
jitter=300
delay=0
loss=0
[settings.down]
bandwidth=0
jitter=300
delay=0
loss=0

[[settings]]
[settings.up]
bandwidth=0
jitter=300
delay=0
loss=0
[settings.down]
bandwidth=0
jitter=300
delay=0
loss=0

[[settings]]
[settings.up]
bandwidth=0
jitter=300
delay=0
loss=0
[settings.down]
bandwidth=0
jitter=300
delay=0
loss=0